// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESERVAS.API.Data;

#nullable disable

namespace RESERVAS.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RESERVAS.API.Entities.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("ACTIVO")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DELETED")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HABITACIONES")
                        .HasColumnType("int");

                    b.Property<decimal?>("LATITUD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LONGITUD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PAIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("NOMBRE")
                        .IsUnique();

                    b.ToTable("HOTELES");
                });

            modelBuilder.Entity("RESERVAS.API.Entities.Reserva", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CHECKIN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CHECKOUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DELETED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ESTADO")
                        .HasColumnType("bit");

                    b.Property<int>("ID_HABITACION")
                        .HasColumnType("int");

                    b.Property<int>("ID_HOTELID")
                        .HasColumnType("int");

                    b.Property<int>("ID_USUARIOID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID_HOTELID");

                    b.HasIndex("ID_USUARIOID");

                    b.ToTable("RESERVAS");
                });

            modelBuilder.Entity("RESERVAS.API.Entities.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("APELLIDOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DELETED")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIRECCION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("RESERVAS.API.Entities.Reserva", b =>
                {
                    b.HasOne("RESERVAS.API.Entities.Hotel", "ID_HOTEL")
                        .WithMany()
                        .HasForeignKey("ID_HOTELID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESERVAS.API.Entities.Usuario", "ID_USUARIO")
                        .WithMany()
                        .HasForeignKey("ID_USUARIOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ID_HOTEL");

                    b.Navigation("ID_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
